<a href="https://colab.research.google.com/github/hemang03/naives_bayes/blob/master/spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import pandas as pd

In [71]:
import numpy as np
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [72]:
df = pd.read_csv('sms_spam.csv')

In [73]:
df.head()

type                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer
stopset = (stopwords.words('english'))
vectorizer = TfidfVectorizer(lowercase=True , stop_words =stopset,use_idf=True , strip_accents ='ascii')

In [75]:
vectorizer.fit(df)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                strip_accents='ascii', sublinear_tf=False,
                token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
                vocabulary=None)

In [76]:
df['type'] = df['type'].apply(lambda x: 1 if x =='spam' else 0) 

In [77]:
df['type'].unique

<bound method Series.unique of 0       0
1       0
2       1
3       0
4       0
       ..
5569    1
5570    0
5571    0
5572    0
5573    0
Name: type, Length: 5574, dtype: int64>

In [78]:
y = df.type

In [79]:
X = vectorizer.fit_transform(df.text).toarray()

In [80]:
X.shape

(5574, 8586)

In [81]:
y.shape

(5574,)

In [82]:
#to split 
split_1 = (df.text[0]).split()
print(split_1)

['Go', 'until', 'jurong', 'point,', 'crazy..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet...', 'Cine', 'there', 'got', 'amore', 'wat...']


In [83]:
len(split_1)

20

In [84]:
max(split_1)

'world'

In [85]:
X[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [86]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [87]:
vectorizer.get_feature_names()[3534]

'gnt'

In [88]:
split_2 = (df.text[1]).split()
print(split_2)

['Ok', 'lar...', 'Joking', 'wif', 'u', 'oni...']


In [89]:
X[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [90]:
max(split_2)

'wif'

In [91]:
len(split_2)

6

In [92]:
## The most freaquent word across all the SMSes
max(vectorizer.get_feature_names())

'zyada'

In [93]:
from sklearn.model_selection import train_test_split 
X_train,X_test , y_train ,y_test = train_test_split(X , y , test_size = 0.2 , random_state =0)

In [94]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train ,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [95]:
y_pred = model.predict(X_test)

In [96]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [97]:
from sklearn.metrics import roc_auc_score
rc = roc_auc_score(y_test , y_pred)

In [98]:
rc

0.8848484848484848

In [99]:
model.score(X_test , y_test)

0.9659192825112107

In [100]:
df.loc[5,'text']

"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv"